### ISSUE TITLE
Align the example images side by side

### ISSUE THREAD

**Issue by ArnavGhosh999** [ArnavGhosh999/INTERACTIVE-ARTWORK-GENERATOR#5]
The A.I generated Images should be aligned side by side and not one below the other

**Comment by nabeelahmad10** [comment]
Tt depends on a certain sceeen width. if the width is around 15-16 inches it will potray side by side but if its less it will be shown as one after another. Anyways I'll make sure it stays the same if you're viewing from screen of any width

**Comment by nabeelahmad10** [comment]
This issue is fixed. Removal of some unnecessary css was done and there is some media queries left to be set. It'll be done soon
